main: me.SuperRonanCraft.BetterRTPAddons.Main
version: ${project.version}
api-version: '1.13'
folia-supported: true
name: BetterRTPAddons
depend: [BetterRTP]
softdepend: [ProtocolLib]

permissions:
  betterrtp.addon.portals:
    description: Ability to use the portals addon commands
  betterrtp.addon.queue:
    description: Ability to join RTP Queue
    default: true
  betterrtp.addon.zone:
    description: Ability to use RTP Zone
    default: true

commands:
  rtpqueue:
    description: Join the RTP Queue
    usage: /rtpqueue
  rtpzone:
    description: Create or manage RTP Zones
    usage: /rtpzone
